from ..math import Color as Color, Matrix4x4 as Matrix4x4, Quaternion as Quaternion, Rectangle as Rectangle, Vector2 as Vector2, Vector3 as Vector3, Vector4 as Vector4
from _typeshed import Incomplete
from io import IOBase
from typing import Callable

class EndianBinaryWriter:
    stream: IOBase
    endian: str
    Length: int
    Position: int
    Encryption: Callable
    def __init__(self, input_: bytes = ..., endian: str = ..., offset: int | None = ..., encrypt_func: Callable | None = ...) -> None: ...
    @property
    def bytes(self): ...
    @property
    def Length(self) -> int: ...
    def dispose(self) -> None: ...
    def write(self, *args): ...
    def write_byte(self, value: int): ...
    def write_u_byte(self, value: int): ...
    def write_bytes(self, value: bytes): ...
    def write_short(self, value: int): ...
    def write_int(self, value: int): ...
    def write_long(self, value: int): ...
    def write_u_short(self, value: int): ...
    def write_u_int(self, value: int): ...
    def write_u_long(self, value: int): ...
    def write_float(self, value: float): ...
    def write_double(self, value: float): ...
    def write_boolean(self, value: bool): ...
    def write_string_to_null(self, value: [str, bytes, bytearray], encoding: str = ...): ...
    def write_aligned_string(self, value: [str, bytes, bytearray], encoding: str = ...): ...
    def align_stream(self, alignment: int = ...) -> None: ...
    def write_quaternion(self, value: Quaternion): ...
    def write_vector2(self, value: Vector2): ...
    def write_vector3(self, value: Vector3): ...
    def write_vector4(self, value: Vector4): ...
    def write_rectangle_f(self, value: Rectangle): ...
    def write_color4(self, value: Color): ...
    def write_matrix(self, value: Matrix4x4): ...
    def write_array(self, command, value: list, write_length: bool = ...): ...
    def write_byte_array(self, value: bytes): ...
    def write_boolean_array(self, value: list): ...
    def write_u_short_array(self, value: list): ...
    def write_int_array(self, value: list, write_length: bool = ...): ...
    def write_u_int_array(self, value: list, write_length: bool = ...): ...
    def write_float_array(self, value: list, write_length: bool = ...): ...
    def write_string_array(self, value: list): ...
    def write_vector2_array(self, value: list): ...
    def write_vector4_array(self, value: list): ...
    def write_matrix_array(self, value: list): ...
