from .. import classes as classes
from ..classes.Object import NodeHelper as NodeHelper
from ..enums import ClassIDType as ClassIDType
from ..exceptions import TypeTreeError as TypeTreeError
from ..files import SerializedFile as SerializedFile
from ..helpers import TypeTreeHelper as TypeTreeHelper
from ..helpers.Tpk import get_typetree_nodes as get_typetree_nodes
from ..streams import EndianBinaryReader as EndianBinaryReader, EndianBinaryWriter as EndianBinaryWriter
from _typeshed import Incomplete
from typing import Dict, List
from ..math import Quaternion, Vector2, Vector3, Vector4, Rectangle, Matrix4x4, Color

DEBUG_TYPETREES: bool

class ObjectReader:
    byte_start: int
    byte_size: int
    type_id: int
    class_id: int
    type: ClassIDType
    path_id: int
    reader: EndianBinaryReader
    assets_file: Incomplete
    data: bytes
    version: Incomplete
    version2: Incomplete
    platform: Incomplete
    build_type: Incomplete
    byte_start_offset: Incomplete
    byte_header_offset: Incomplete
    byte_base_offset: Incomplete
    byte_size_offset: Incomplete
    serialized_type: Incomplete
    is_destroyed: Incomplete
    stripped: Incomplete
    def __init__(self, assets_file: SerializedFile, reader: EndianBinaryReader) -> None: ...
    def write(self, header, writer: EndianBinaryWriter, data_writer: EndianBinaryWriter): ...
    def set_raw_data(self, data) -> None: ...
    @property
    def container(self): ...
    @property
    def Position(self): ...
    def reset(self) -> None: ...
    def read(self, return_typetree_on_error: bool = ...): ...
    def get(self, key, default: Incomplete | None = ...): ...
    def __getattr__(self, item: str): ...
    def dump_typetree(self, nodes: list = ...) -> str: ...
    def dump_typetree_structure(self) -> str: ...
    def get_typetree_nodes(self, nodes: list = ...) -> list: ...
    def read_typetree(self, nodes: list = ..., wrap: bool = ...) -> dict: ...
    def save_typetree(self, tree: dict, nodes: list = ..., writer: EndianBinaryWriter = ...): ...
    def get_raw_data(self) -> bytes: ...
    def set_raw_data(self, data) -> None: ...

    def read(self, *args) -> None: ...
    def within_size(self): ...
    def read_bytes(self, num) -> bytes: ...
    def read_byte(self) -> int: ...
    def read_u_byte(self) -> int: ...
    def read_short(self) -> int: ...
    def read_int(self) -> int: ...
    def read_long(self) -> int: ...
    def read_u_short(self) -> int: ...
    def read_u_int(self) -> int: ...
    def read_u_long(self) -> int: ...
    def read_float(self) -> float: ...
    def read_double(self) -> float: ...
    def read_boolean(self) -> bool: ...
    def read_string(self, size: Incomplete | None = ..., encoding: str = ...) -> str: ...
    def read_string_to_null(self, max_length: int = ...) -> str: ...
    def read_aligned_string(self) -> str: ...
    def align_stream(self, alignment: int = ...) -> None: ...
    def read_quaternion(self) -> Quaternion: ...
    def read_vector2(self) -> Vector2: ...
    def read_vector3(self) -> Vector3: ...
    def read_vector4(self) -> Vector4: ...
    def read_rectangle_f(self) -> Rectangle: ...
    def read_color4(self) -> Color: ...
    def read_byte_array(self) -> bytes: ...
    def read_matrix(self) -> Matrix4x4: ...
    def read_array(self, command, length: int) -> list: ...
    def read_array_struct(self, param: str, length: int = ...) -> list: ...
    def read_boolean_array(self, length: int = ...) -> List[bool]: ...
    def read_u_short_array(self, length: int = ...) -> List[int]: ...
    def read_short_array(self, length: int = ...) -> List[int]: ...
    def read_int_array(self, length: int = ...) -> List[int]: ...
    def read_u_int_array(self, length: int = ...) -> List[int]: ...
    def read_u_int_array_array(self, length: int = ...) -> List[int]: ...
    def read_long_array(self, length: int = ...) -> List[int]: ...
    def read_u_long_array(self, length: int = ...) -> List[int]: ...
    def read_float_array(self, length: int = ...) -> List[float]: ...
    def read_string_array(self, length: int = ...) -> List[str]: ...
    def read_vector2_array(self, length: int = ...) -> List[Vector2]: ...
    def read_vector4_array(self, length: int = ...) -> List[Vector4]: ...
    def read_matrix_array(self, length: int = ...) -> List[Matrix4x4]: ...
    def real_offset(self) -> int: ...
    def read_the_rest(self, reader: ObjectReader) -> bytes: ...
